const errorCodes = {
  INFORMATIONAL_CODE_CONTINUE: 100,
  INFORMATIONAL_CODE_SWITCHING_PROTOCOL: 101,
  SUCCESS_CODE_OK: 200,
  SUCCESS_CODE_NO_CONTENT: 204,
  SUCCESS_CODE_CREATED: 201,
  REDIRECTIONAL_CODE_CREATED: 300,
  REDIRECTIONAL_CODE_MOVED_PERMANENTLY: 301,
  REDIRECTIONAL_CODE_FOUND: 302,
  CLIENT_ERROR_BAD_REQUEST: 400,
  CLIENT_ERROR_UNAUTHORIZED: 401,
  CLIENT_ERROR_FORBIDDEN: 403,
  CLIENT_ERROR_NOT_FOUND: 404,
  SERVER_ERROR_INTERNAL_SERVER_ERROR: 500,
  SERVER_ERROR_NOT_INPLEMENTED: 501,
  SERVER_ERROR_BAD_GATEWAY: 502,
  SERVER_ERROR_SERVICE_UNAVAILABLE: 503,
};

const errorMessages = {
  INFORMATIONAL_CODE_CONTINUE: "Continue",
  INFORMATIONAL_CODE_SWITCHING_PROTOCOL: "switching Protocol",
  SUCCESS_CODE_OK: "Ok",
  SUCCESS_CODE_NO_CONTENT: "No Content",
  SUCCESS_CODE_CREATED: "Success Created",
  REDIRECTIONAL_CODE_CREATED: "Redirectional Created",
  REDIRECTIONAL_CODE_MOVED_PERMANENTLY: "Moved Permanently",
  REDIRECTIONAL_CODE_FOUND: "Code Found",
  CLIENT_ERROR_BAD_REQUEST: "Bad Request",
  CLIENT_ERROR_UNAUTHORIZED: "Unauthorized",
  CLIENT_ERROR_FORBIDDEN: "FOrbidded",
  CLIENT_ERROR_NOT_FOUND: "Not Found",
  SERVER_ERROR_INTERNAL_SERVER_ERROR: "Internal Server Error",
  SERVER_ERROR_NOT_INPLEMENTED: "Not Implemented",
  SERVER_ERROR_BAD_GATEWAY: "Bad Gateway",
  SERVER_ERROR_SERVICE_UNAVAILABLE: "Service Unavailable",
};

export { errorCodes, errorMessages };
